### ISSUE TITLE
implement manifest generation

### ISSUE THREAD

**Issue by JonKohler** [nutanix/PowerShell#13]
We need to dynamically generate the psd1 and psm1 files, which I have hand crafted today.

I have a feeling we can borrow some code from the upstream powershell project, so that it just generates on build.

This likely means moving away from typical make file and to something like build.ps1 and just have powershell as the builder file instead.

You can get a feel for what others are doing here: 
https://www.powershellgallery.com/packages/Azure/5.3.0
http://blog.tintoy.io/2017/02/building-modules-for-powershell-core/

For example, if you go to the Azure project, and click file list - you can see how they structured their manifests.

**Comment by mallochine** [comment]
Fixed in commit de97ae2c6459ac07bcf9bdb6998cd9dd3bee8d6b
