### ISSUE TITLE
implement OSX builds in travisCI

### ISSUE THREAD

**Issue by JonKohler** [nutanix/PowerShell#17]
since this is cross platform, we need OSX coverage. 

This can be done via Travis, in addition to the linux coverage we have today.

Should be able to borrow the structures from upstream powershell, here: 
https://github.com/PowerShell/PowerShell/blob/master/.travis.yml

**Comment by mallochine** [comment]
Fixed in bb9e358dbda09d75c589ca5bb717368ac187a689
