### ISSUE TITLE
Move from WebClient/WebRequest to HttpClient (DE0003: WebRequest shouldn't be used)

### ISSUE THREAD

**Issue by JonKohler** [nutanix/PowerShell#37]
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-2.1

WebClient/WebRequest is deprecated. Please move the util web connections to httpclient: 
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-2.1

**Comment by mallochine** [comment]
Fixed in 752ab68e72ded3afdba4b0067e25bc19fbeaef73
