### ISSUE TITLE
Migrate Travis to CircleCI

### ISSUE THREAD

**Issue by JonKohler** [nutanix/PowerShell#44]
We're moving to CircleCI for other "stuff", and I'd like all of our stuff to be on one platform.

I haven't figured out with CCI, for this specific use case, gives us what we need or not, so we need to do a bit of investigation to see what the dotnet 2.1++ support looks like

**Comment by mallochine** [comment]
Fixed, see `.circleci/config.yml`

https://circleci.com/gh/nutanix/PowerShell/16
