### ISSUE TITLE
GetAllVms return only 20 VMs

### ISSUE THREAD

**Issue by sergey-s-bykov** [nutanix/PowerShell#46]
**Describe the bug**
We send empty POST request to /vms/list and as result, remote endpoint returns only first 20 VMs.
In the response we this:
```
{
  "api_version": "3.0",
  "metadata": {
    "total_matches": 353,
    "kind": "vm",
    "length": 20, <<<<<<<<
    "offset": 0
  },
...
```
So, due to this behavior, we do not get all VMs, but only 20. 

**To Reproduce**
1) Create a cluster with more than 20 VMs
2) Using Connect to the cluster 
3) Execute Get-VM and measure the resulting object: 
```
PS C:\> $vms = Get-VM
PS C:\> $vms.Length
20
```

**Expected behavior**
Get-VM without any arguments must return all cluster VMs. 

**Environment (please complete the following information):**
 - AOS: 5.5.2
 - PowerShell version: 6.1.0-Preview3

**Comment by Misha305** [comment]
This is a limitation of the API. The default is 20 the max is 500 so you need to offset and send multiple requests.
https://www.nutanix.dev/2019/06/13/the-five-hundred-500-vms-via-v3-api/

**Comment by sergey-s-bykov** [comment]
The issue was resolved long time ago.
