### ISSUE TITLE
Set header X-Nutanix-Client-Type to cmdlets

### ISSUE THREAD

**Issue by JonKohler** [nutanix/PowerShell#7]
In the current shipping code, we define a custom client type header (X-Nutanix-Client-Type), such that the backend can track where requests are coming from. We need to forward port this logic into this SDK

See existing code here: /main/prism/cmdlet_code_generator/src/main/resources/csharp/common/NutanixBaseCmdlets.cs
```
313                // Adding custom header for client tracking
314                request.Headers.Add("X-Nutanix-Client-Type", "cmdlets");
```

**Comment by mallochine** [comment]
I tagged it as "PowershellSDK" instead of "cmdlets", to avoid collision with the old SDK.

**Comment by JonKohler** [comment]
Thanks alex. If we're going to change it (which I agree is a good idea and the right call), we need to sync on a standard with the REST committee, since we're doing something similar with things like Chef/Terraform, we should have a consistent header standard. Will leave it as-is for now and throw in a JIRA to the REST project

**Comment by JonKohler** [comment]
I've filed this under REST-335

**Comment by JonKohler** [comment]
reopening pending the feedback from the REST committee about the standard for this, so we only have to release it once

**Comment by JonKohler** [comment]
changed to Nutanix.Powershell.SDK
